pipeline {
  agent { label 'first'}
  stages {
    stage('installing dependencies') {
      steps {
        sh '''
        cd vote && ls -l
        pip3 install -r requirements.txt
        '''
      }
    }
    stage('Sonarqube scan') {
      steps {
      withSonarQubeEnv('sonarqube ec2') {
      sh '''
          cd vote
          sonar-scanner
      '''
      }
      }
    }
    stage('Building Docker Images') {
      steps {
        sh '''
          cd vote
          docker build -t divyanshuk/vote:$BUILD_NUMBER -t divyanshuk/vote:latest .
        '''
      }
    }
    stage("Docker Image Security Scan") {
      steps{
        sh 'echo "installing depend"'
        }
    }
    stage("Docker image to Registry") {
       steps{
        sh 'echo "installing depend"'
        }
    }
  }
}
