pipeline {
  agent { label 'first'}
  stages {
    stage('installing dependencies') {
      steps {
        sh 'cd vote && ls -l'
        sh 'pip3 install -r requirements.txt'
        sh 'cd ..'
      }
    }
    stage('Sonarqube scan') {
      steps {
        sh 'echo "installing depend"'
      }
    }
    stage('Building Docker Images') {
      steps {
        sh 'echo "installing depend"'
      }
    }
    stage("Docker Image Security Scan") {
      steps{
        sh 'echo "installing depend"'
        }
    }
    stage("Docker image to Registry") {
       steps{
        sh 'echo "installing depend"'
        }
    }
  }
}
