apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    tags: voting-application
spec:
  type: NodePort
  selector:
    app: vote-app
  ports:
  - nodePort: 5000
    port: 80
    targetPort: 80
