pipeline {
  agent { label 'first'}
  stages {
    stage('Restore') {
      steps {
        sh "dotnet restore ./worker/Worker.csproj"
      }
    }
        stage('Clean') {
      steps {
        sh "dotnet clean ./worker/Worker.csproj"
      }
    }
        stage('Build') {
      steps {
        sh "dotnet build ./worker/Worker.csproj"
      }
    }
    stage('Sonarqube scan') {
      steps {
      withSonarQubeEnv('sonarqube ec2') {
      sh '''
          cd vote
          sonar-scanner
      '''
      }
      }
    }
    
    stage('Building Docker Images') {
      steps {
        sh '''
          echo '2nd'
        '''
      }
    }
    stage("Docker Image Security Scan") {
      steps{
        sh 'echo "3rd"'
        }
    }
  }
}